name: Ubuntu-Server

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: fastai/workflows/ssh@master
      with:
        ssh_key: ${{ secrets.SSH_KEY }}
        key_file: id_ecdsa

    - name: Run Ubuntu script
      run: bash ubuntu-run.sh

    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      timeout-minutes: 3940
